Update fpgroup.py
unused

TODO:
>>> if 1:
    f2 = free_group(['a', 'b'])
    f3 = free_group(['x', 'y', 'z'])
    a, b = f2.gens
    x, y, z = f3.gens
    z333 = f3/[x**3, y**3, z**3, x*y*x**-1*y**-1, x*z*x**-1*z**-1, z*y*z**-1*y**-1]
    relrplc = [w.mapped([a**2, b**2, a*b]) for w in z333.rels]
    nc333 = f2.normalclosure(relrplc)
    dcst = grp_coset(nc333.basis, nc333.rels + relrplc)
    sub2 = f2[a**2, b**2, a*b]
    z23 = sub2/nc333

    
['a**6', 'a**3*b*a**-2*b**-1*a**-1', 'a**2*b**2*a**-2*b**-2', 'a*b*a*b*a*b', 'a*b**2*a**-1*b**-2', 'b**6']
>>> z23.filt.lp_tbl[0]
['a**2', 'a*b', 'b**2', 'b**-1*a**-1', 'a**-2', 'b*a', 'a*b**-1', 'a**-1*b**-1', 'b*a**-1', 'b**-2']

Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    z23.filt.lp_tbl[0]
  File "E:\MyPro\games\Labyrinth\py\fpgroup.py", line 486, in lp_tbl
    self.replace_loop_words(self.subs + self.rels)
  File "E:\MyPro\games\Labyrinth\py\fpgroup.py", line 446, in replace_loop_words
    raise RuntimeError("bone shouldn't be closed")
RuntimeError: bone shouldn't be closed
>>> z23.filt.replace_loop_words(relrplc)
['a**2', 'b**2', 'a**-2', 'b**-2', 'a*b', 'b**-1*a**-1', 'b*a**-1']

Traceback (most recent call last):
  File "<pyshell#22>", line 1, in <module>
    z23.filt.replace_loop_words(relrplc)
  File "E:\MyPro\games\Labyrinth\py\fpgroup.py", line 457, in replace_loop_words
    raise RuntimeError("unsolved loop relation")
RuntimeError: unsolved loop relation
>>>